spring:
  application:
    name: sos-rota
  main:
    web-application-type: none

  # Configuração PostgreSQL - Banco de dados relacional conforme PDF do projeto
  datasource:
    url: jdbc:postgresql://localhost:5432/sosrota_db
    username: sosrota_user
    password: sosrota_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

logging:
  level:
    root: INFO
    sosrota: DEBUG

